apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mystok-gcp-java-env-secret
  namespace: default
spec:
  encryptedData:
    BUCKET_NAME: AgANqalm50EuVasoWwOm33AcPEX9ML3hgeYyiCHRuS9DnambWJIF+0wEw+P/DGkvELJVhUKtaeB84CrT8CPE1Jfl3BvjSxchCJ8VqQU90B0pCofK6Z7fYsmkp4CWyfCefZNJWxIe0QFW82oiDeFpsKpXPiUwT/5kUB4FP75cRM9OHpuEJORru30ug8bMmuWcFx3I1kn+YY036ENnJUy/GFtmJ2glK2yIt02v9NzpejXAP5dpE70JEm6scSXKMvzpfe9H9/4FdsY1VMk9MUXSpEHOsYIHKid8hFU1cH6akq89+EGpY2vuAIKNbiaPcI0/b/1g6cCxJLk+TcrdY6M3904u8U+ME85BS+CRNSXxv3UvCfgn3QwYwfGoW/3hDjTI/7hnGZoIjco6GXdye/1uaWOcmjv6l2aaT7mCsfqYnewRp4scL1ZuWN1cMWhWa1aDBWMrQtUDwielQsuJh534CrV72NaL+ZRImsRxSo8aXRNDHAeAc7OGEC7HzkgMyJ4iKu+Cgr0CL6GWACwzva0c2zLz3xysxLezvUsgDszL84qAAg7/AqlXMZvhmcR/p77hnQGgNRK2WZJWtEfMmQgFSps/cPlk+46lqpyov9eUgyLRqrlQZFMO8dlT+15u6d87BB2cblwnOIHDVmJuOp1esFZ8N9vp9yCAe/KGv3564v8Ba4PUBvSmDcIkygPga4AFY06kYnHQi4ROOiuvv4/bs+g7VBgHs/4ePbl5885I
    PROJECT_ID: AgA+JxHeOcDhS8mDBUZei/FA6aMgykvNKXNbMVI+12jeTXFh13vq78EfAQ3hfyc2Fs927k/uifl2mKI9BNSl9ZoQ1hP7j1PLa8totUt+bPw91c1X0isQgDDBjPOwTlbSQfXYlWi08McglE5Ixy7hJsG2wTgtboB6FM63LubGcabI7qmeIeokkwpXs8VmCyoVNfGeM128vGjVooEosp2FzhepIKkStiNttnJ+yzImxWvpKU0UzYRbfqzYP7b8gfFok8a/lKPN0CXggiNhkTTmXXb5ntf8iGltYpPWc7P/chkaOw+Sq3oUJIp/yY3Yga/Q+0/vCh3/aSF9EN/0kexQi6vsC7Hs4KJFW5dzJhGChWSP1Dd9yB27cJ68ChElhF6JkFNjMtIjeRWl7Xrw9r6NYfGdxtif4iP9T0vwojG7nNWjJcGIMzIgTh9mGRCKNCvqWwtovvX06lbDfMzUZd7YHt6bQ4x/qim0AACcUQkngkoNWueDCHy+vXxdtORRAg7Zm3wegCt6QamCd5nOBO0O6kWqumW1M4Ba4IhVe6D26Ky0zs2VId+6TsqyXOEDV4LGwSX6+RQEf4JVe0ZO8HGavkwuX1eEwTmQ/iWc1WJSBeODFOSXxC/Wai+X/loMxrLt9lRWpxOYxQrKL6UDxJO6fQQno1h47pZpoAo1tZBjNbo/1v0zXZwedViK75g2QJz4eEF7EtksaBoLIVb423cPBpot7BxHKi2M
  template:
    metadata:
      creationTimestamp: null
      name: mystok-gcp-java-env-secret
      namespace: default
    type: Opaque

